spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: service_route
          uri: http://localhost:9000
          predicates:
            - Path=/gateway/test/**
        - id: camping-service
          uri: lb://camping-service # Eureka 서버에서 로드밸런싱
          predicates:
            - Path=/api/camping/**
  application:
    name: spring-gateway

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/
    register-with-eureka: true
    fetch-registry: true



management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
#  server:
#    port: 1234   # actuator 한 프로젝트에 두개의 포트 사용가능 원하는 포트 번호
  endpoints:
    enabled-by-default: false
    web:
      base-path: /monitoring   # 원하는 경로
      exposure:
        include: "info, health, prometheus"
    jmx:
      exposure:
        exclude: "*"